spring.application.name=demo-bai8-springmvc

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=5MB

app.upload.dir=${user.home}/demo-uploads

# Phân trang danh sách user
app.users.page-size=5
